### ISSUE TITLE
Expose more fields of SafariService

### ISSUE THREAD

**Issue by codecomeon** [swan-io/react-native-browser#10]
### Why it is needed?

I want to customized the presentStyle of SafariService, maybe we can expose all the fields of SafariService for convenient?

**Comment by zoontek** [comment]
I'm not a fan of exposing native options directly, it defeats the purpose of multi-platforms.

I will probably recreate similar animations for Android instead.

**Comment by zoontek** [comment]
I added the `fade` animation type: https://github.com/swan-io/react-native-browser/releases/tag/0.3.0
