### ISSUE TITLE
Add onRedirect callback

### ISSUE THREAD

**Issue by c100k** [swan-io/react-native-browser#2]
### Why it is needed?

From the docs :

> Once the redirect URL is visited (a GET hits your server), handle the result and perform a server redirect to com.company.myapp://close?success=true to close the browser (and pass any data back to your app using query params ✨).

This works well when we manage the server behind the webpage being opened, but not when it's a third party website.

For example, in an "OAuth dance", the third party will redirect to the redirect URL we defined when declaring the application on their side. Some of them do not allow to put a deeplink there, forcing an HTTP URL. Which makes it impossible to have the `onClose` callback called with the deeplink. I can link my mobile app present in the stores to illustrate if need be.

### Possible implementation

One of the solutions I imagined is to have an `onRedirect` callback, having the same signature as `onClose`. This way, on the mobile app side, we could listen to the URL changes and mimick the `onClose` callback when needed.

### Code sample

```ts
import { openBrowser } from "@swan-io/react-native-browser";

openBrowser("https://swan.io", {
  dismissButtonStyle: "close", // "cancel" | "close" | "done" (default to "close")
  barTintColor: "#FFF", // in-app browser UI background color
  controlTintColor: "#000", // in-app browser buttons color
  onOpen: () => {
    // fired on browser opened
    // useful to switch the StatusBar color, for example
  },
  onClose: (url) => {
    // fired on browser closed
    // url will be defined if the browser has been closed via deeplink
  },
  onRedirect: (url) => {
    // fired on each page redirect within the browser
    // url corresponds to the new URL of the browser (i.e. window.location.href)
  },
}).catch((error) => {
  console.error(error);
});
```

**Comment by zoontek** [comment]
@c100k You can't do that without a dedicated deeplink (at least in in-app browsers)

**Comment by c100k** [comment]
Ah ! Indeed : https://stackoverflow.com/questions/42192701/detect-url-change-in-sfsafariviewcontroller

Closing then. Thanks for your quick reply.
