### ISSUE TITLE
Custom headers and change url detection

### ISSUE THREAD

**Issue by DanielRiera** [swan-io/react-native-browser#8]
### Why it is needed?

Hi! 

I need send headers to target url, example "Authorization" and need detect change url for call custom functions on my app.

For Android & iOS

Thanks for this package :)

**Comment by zoontek** [comment]
> I need send headers to target url, example "Authorization"

What do you call target url? the one opened by the browser?

> need detect change url for call custom functions on my app

This is not possible with in-app browsers. See the browsers as a black box.

**Comment by DanielRiera** [comment]
1. Yes the url open on browser, other packages have support on android.

2. Ok, On iOS the close url is undefined, i not try on android.

**Comment by zoontek** [comment]
> Yes the url open on browser, other packages have support on android.

This is unfortunately possible on Android, but not on iOS. This packages makes the choice of using a common config, with few options but that work identically on both platforms given their limitations.

**Comment by DanielRiera** [comment]
Ok, no problem thanks you for reply :)
