### ISSUE TITLE
openBrowser not work on android

### ISSUE THREAD

**Issue by chramos** [swan-io/react-native-browser#9]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

I have a simple code to open the browser in my app:
```js
 <Touchable
              onPress={() => {
                openBrowser('https://www.anota.app/terms', {
                  onOpen: () => {
                    console.log('BROWSER IS OPEN');
                  },
                }).catch(e => console.error(e));
              }}>
              <Text color="blue">termos de uso</Text>
            </Touchable>
```

once I press in this text, I can see the log in the metro console, but nothing happens.

the same code is working on iOS

### Library version

0.2.2

### Environment info

```shell
System:
  OS: macOS 14.1
  CPU: (12) arm64 Apple M3 Pro
  Memory: 106.77 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.1
    path: ~/.nvm/versions/node/v20.12.1/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.1/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/henriqueramos/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.22
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/henriqueramos/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. install the package
2. call the openBrowser method with a valid url

### Reproducible sample code

```js
<Touchable
              onPress={() => {
                openBrowser('https://www.anota.app/terms', {
                  onOpen: () => {
                    console.log('BROWSER IS OPEN');
                  },
                }).catch(e => console.error(e));
              }}>
              <Text color="blue">termos de uso</Text>
            </Touchable>
```

**Comment by zoontek** [comment]
@chramos Works great in the example app, or in our own app, with multiple Android simulators and multiple devices. I just made a test with [the example app](https://github.com/swan-io/react-native-browser/tree/main/example) and your website / reproduction code:

https://github.com/swan-io/react-native-browser/assets/1902323/e00000d4-602a-4fad-a755-a6788cec8919

I think it might not be correctly installed / build. Try [clearing the gradle cache](https://github.com/pmadruga/react-native-clean-project) and rebuild your app.

You can also try the example app to determine if it indeed come from the library or your app. If it's the second option, and nothing seems to fix it, we are gonna need more infos (are you trying on a simulator, a device? Does it has Google Play services and Chrome installed?) and probably a reproduction repository.

**Comment by chramos** [comment]
@zoontek, you have asked if it has Chrome installed and yes, it has..
the issue was that I had never opened the Chrome app, right after opening it everything started to work as expected.

thank you for the quick reply.
